language: objective-c
osx_image: xcode8.1
env:
  global:
  - FRAMEWORK_NAME=ImageLoader
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
install:
- gem install cocoapods
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -project ${FRAMEWORK_NAME}.xcodeproj -scheme $FRAMEWORK_NAME
  -sdk iphonesimulator10.1 -configuration Release | xcpretty -c
deploy:
  provider: releases
  api_key:
    secure: 0KI7EtLe3celdLi3NQ1GW4ZesPUPIftbAFGhsZXx18mgFPNt/bTVerGxQuRpfZMTwxWTgOr9aR+AHVsLgfcmnx+z37eMEPFrgEyr8QsjMOeILhviXNnv/BlWpC+EPbR15fNy6XHpP3PzB0vz/RQpcL2DEk8GNiYnc7VSK+STQ684zw5vvF8Aie1NoCOabJWINncscda5LOdiT7120Z7iIFcJsfDr5Ia/FzgVrQIwTHMtC4M31O3+MAKsSKq0eXKJMD3Yzhzonf0CeyWHYO6ARYEr4y2tGO6/eciRH+noP0auvf5hl4EkLfpf4FMn3BE5Rrcuq2b70qXZS9nggheKqjCVi/A64MdC2iFKsH4lodKAo2N1MTzyVcwpF8kWU4Fuc1I7jVW5r9JNUUrLIXT/jtFf3vFoNmoCgwGquH/v6N6HnQg31QN29GWEzPb4HwlGz1LVnvYVWMHCJpTgdPgnptpx5rcISh5wT41rAiTgXWrHP5CIuOHRozigrj294AgKyBMeDdO/VV7rLwcai/lNtfoEAfDMzUCNV5TbwDQjh5cquVkA/zzu1U/5hpYQZmGLEeZG4D8VwW2ltPh0umoPn6M0C8gbqDsrpmCd/7plgNzYKscTkc/h9KK0oIr79e8ILC61cniaWuS6Cmle/Pqlq30Gso5PZSLcnODYCI7wN+A=
  file: "$FRAMEWORK_NAME.framework.zip"
  on:
    repo: paulemmanuel-garcia/ImageLoader
    tags: true
